node_js:
  - stable
  - 8
sudo: false
language: node_js
before_script:
  - 'curl https://sh.rustup.rs -sSf | sh -s -- -y -v'
  - 'export PATH="$HOME/.cargo/bin:$PATH"'
  - 'sh scripts/install.sh'
script:
  - 'npm test'
# after_success: "npm i -g codecov && npm run coverage && codecov"
