node_js:
  - stable
  - 8
sudo: false
language: node_js
before_script:
  - 'curl https://sh.rustup.rs -sSf | sh -s -- -y -v'
  - 'export PATH="$HOME/.cargo:$PATH"'
  - 'rustup update nightly'
  - 'rustup target add wasm32-unknown-unknown --toolchain nightly'
  - 'cargo install --git https://github.com/alexcrichton/wasm-gc'
script:
  - 'npm test'
# after_success: "npm i -g codecov && npm run coverage && codecov"
